name: Module Submission
description: Preferred Magisk Module submission template
title: '[Module] module_id'
body:
  - type: markdown
    attributes:
      value: >
        ## Please read

        - ID must match the id in module.prop

        - Once approved, your module will be added to our repo as
        http://github.com/magisk-modules-alt-repo/example_module

        - Read all requirements before submit for approval:
          - https://github.com/Magisk-Modules-Alt-Repo/submission#source-code-guidelines
          - https://github.com/Magisk-Modules-Alt-Repo/submission#general-guidelines
  - type: input
    id: module-id
    attributes:
      label: ID
      placeholder: example_module
    validations:
      required: true
  - type: input
    id: module-name
    attributes:
      label: Name
      placeholder: Example Module
    validations:
      required: true
  - type: textarea
    id: module-description
    attributes:
      label: Description
      placeholder: A simple module that does this, that, and the other thing.
    validations:
      required: true
  - type: input
    id: module-link
    attributes:
      label: Module repository link
      placeholder: https://www.github.com/username/repo
    validations:
      required: true
  - type: input
    id: module-source-code
    attributes:
      label: Source code link (for compiled binaries/APKs)
      placeholder: https://www.github.com/username/repo
  - type: dropdown
    id: antifeatures
    attributes:
      label: Anti-Features
      description: >-
        - **Ads** — advertising - **Tracking** — tracks and/or reports your
        activity to somewhere, even when it can be turned off - **Non-Free
        Network Services** — promotes or depends entirely on a non-changeable or
        non-free network service - **Non-Free Addons** — promotes other
        non-libre apps or plugins - **Non-Free Dependencies** — needs a
        non-libre app to work (e.g. Google Maps, Market) - **NSFW** — contains
        content that the user may not want to be publicized or visible
        everywhere - **Upstream Non-Free** — upstream source code is not libre,
        and this version has those parts replaced or rewritten - **Non-Free
        Assets** — non-libre media in things that are not code (e.g. images,
        sound, music, 3D-models, or video) - **Known Vulnerability** — known
        security vulnerability - **Disabled Algorithm** — signed using an unsafe
        algorithm - **No Source Since** — source code no longer available,
        making new releases impossible - **Obfuscation** — module includes
        obfuscated code - **UnaskedRemoval** — module removes app, permissions
        and other modules without approval
      multiple: true
      options:
        - Advertising (Ads)
        - Known Vulnerability (KnownVuln)
        - NSFW (NSFW)
        - No Source Since (NoSourceSince)
        - Non-Free Addons (NonFreeAdd)
        - Non-Free Assets (NonFreeAssets)
        - Non-Free Dependencies (NonFreeDep)
        - NonFreeNet (NonFreeNet)
        - Tracking (Tracking)
        - Upstream Non-Free(UpstreamNonFree)
        - Obfuscation (Obfuscation)
        - Unasked removal (UnaskedRemoval)
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
