name: "Comment on \"deadline: 2 weeks\" label"

on:
  issues:
    types: [labeled]

jobs:
  comment:
    if: "contains(github.event.label.name, 'deadline: 2 weeks')"
    runs-on: ubuntu-latest

    steps:
    - name: Post comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey @${{ github.event.issue.user.login }},

          your module submission was labeled with a deadline of **two weeks**. If you don't response within the two weeks your module will be rejected.

          Rest regards,
          The MMAR Team
