name: Comment on "deadline; 2 weeks" label

on:
  issues:
    types: [labeled]

jobs:
  comment:
    if: contains(github.event.label.name, 'deadline; 2 weeks')
    runs-on: ubuntu-latest

    steps:
    - name: Post comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          This issue has been labeled with "deadline: 2 weeks". Please make sure to address it within the given timeframe.
