name: "Comment on \"2-weeks-deadline\" label"

on:
  issues:
    types: [labeled]

jobs:
  comment:
    if: contains(github.event.label.name, "2-weeks-deadline")
    runs-on: ubuntu-latest

    steps:
    - name: Post comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          This issue has been labeled with "2-weeks-deadline". Please make sure to address it within the given timeframe.
