name: Check for Magisk Module Updates

on:
  # schedule:
  #   - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: "@MagiskModulesAltRepo"
        run: python tg.py

      - name: Upload state file
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: last-versions
          path: last_versions.json

      - name: Download state file
        if: failure()
        uses: actions/download-artifact@v3
        with:
          name: last-versions
