name: Telegram CI

on:
    workflow_dispatch:
        inputs:
            title:
              required: false
              default: '**CI Manager**'
              description: 'Title'
            message:
              required: false
              default: 'No message.'
              description: 'Message'
            send_telegram:
              description: 'Send to Telegram'
              required: true
              default: true
              type: boolean
            buildType:
              description: "Build Type"
              type: choice
              required: true
              default: 'Aplha'
              options:
               - 'Release'
               - 'Playstore'
               - 'ReleaseCandidate'
               - 'Beta'
               - 'Alpha'
               - 'Debug'
               - 'DebugMin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install telebot

      - name: Parse input
        run: |
            BUILD_TYPE_CASED=$(echo "${{ inputs.buildType }}" | sed 's/^\(.\)/\L\1/')
            echo "BUILD_TYPE_CASED=$BUILD_TYPE_CASED" >> $GITHUB_ENV

            echo "${{ inputs.message }}" > test.txt
            BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
            VERSION=$(git rev-list --count HEAD)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: Upload files to Telegram
        if: github.event.inputs.send_telegram == 'true'
        run: |
            python3 scripts/telegram-ci.py \
              --token "${{ secrets.TELEGRAM_BOT_TOKEN }}" \
              --channel_id @kaklakaka \
              --file_path test.txt \
              --buttons """[
                {
                    "text": "View Run",
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]""" \
              --message """${{ inputs.title }}
            #ci_$VERSION

            Build on $BUILD_DATE.
                
            ${{ inputs.message }}

            Type: $BUILD_TYPE_CASED
            """
