# Workflow File
name: Publish Extension
on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true
        description: "Repo Name (Internal only)"
  
      verified:
        type: boolean
        description: "Verify module"
        required: false
        default: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  IS_SYNC: ${{ github.event_name == 'schedule' || startsWith(github.event.head_commit.message, '[sync]') }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Update my-file.json description
        uses: jossef/action-set-json-field@v2.1
        with:
          file: my-file.json
          field: verified
          value: my custom data

      - name: Test
        run: |
          echo "repo_name: ${{ github.event.inputs.repo_name }}"
          echo "preRelease: ${{ github.event.inputs.repo_name }}"

